title: "MY PORTFOLIO"
description: "A Neo-Brutalist showcase of my games and programs."
baseurl: ""
url: "https://jongcheol-pak.github.io"

markdown: kramdown
# theme: minimal # We are using custom layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/

